(cl:in-package openpose_ros_msgs-msg)
(cl:export '(NUM_BODY_KEY_POINTS_WITH_NON_ZERO_PROB-VAL
          NUM_BODY_KEY_POINTS_WITH_NON_ZERO_PROB
          NUM_FACE_KEY_POINTS_WITH_NON_ZERO_PROB-VAL
          NUM_FACE_KEY_POINTS_WITH_NON_ZERO_PROB
          NUM_RIGHT_HAND_KEY_POINTS_WITH_NON_ZERO_PROB-VAL
          NUM_RIGHT_HAND_KEY_POINTS_WITH_NON_ZERO_PROB
          NUM_LEFT_HAND_KEY_POINTS_WITH_NON_ZERO_PROB-VAL
          NUM_LEFT_HAND_KEY_POINTS_WITH_NON_ZERO_PROB
          BODY_BOUNDING_BOX-VAL
          BODY_BOUNDING_BOX
          FACE_BOUNDING_BOX-VAL
          FACE_BOUNDING_BOX
          BODY_KEY_POINTS_WITH_PROB-VAL
          BODY_KEY_POINTS_WITH_PROB
          FACE_KEY_POINTS_WITH_PROB-VAL
          FACE_KEY_POINTS_WITH_PROB
          RIGHT_HAND_KEY_POINTS_WITH_PROB-VAL
          RIGHT_HAND_KEY_POINTS_WITH_PROB
          LEFT_HAND_KEY_POINTS_WITH_PROB-VAL
          LEFT_HAND_KEY_POINTS_WITH_PROB
))