# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openpose_ros_msgs/OpenPoseHumanList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import openpose_ros_msgs.msg
import std_msgs.msg

class OpenPoseHumanList(genpy.Message):
  _md5sum = "520d81a8dc226a535b021aef637b0340"
  _type = "openpose_ros_msgs/OpenPoseHumanList"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
Header image_header
int32 num_humans
OpenPoseHuman[] human_list
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: openpose_ros_msgs/OpenPoseHuman
int32 num_body_key_points_with_non_zero_prob
int32 num_face_key_points_with_non_zero_prob
int32 num_right_hand_key_points_with_non_zero_prob
int32 num_left_hand_key_points_with_non_zero_prob
BoundingBox body_bounding_box
BoundingBox face_bounding_box
PointWithProb[25] body_key_points_with_prob
PointWithProb[70] face_key_points_with_prob
PointWithProb[21] right_hand_key_points_with_prob
PointWithProb[21] left_hand_key_points_with_prob
================================================================================
MSG: openpose_ros_msgs/BoundingBox
float64 x
float64 y
float64 width
float64 height
================================================================================
MSG: openpose_ros_msgs/PointWithProb
float64 x
float64 y
float64 prob"""
  __slots__ = ['header','image_header','num_humans','human_list']
  _slot_types = ['std_msgs/Header','std_msgs/Header','int32','openpose_ros_msgs/OpenPoseHuman[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,image_header,num_humans,human_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpenPoseHumanList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.num_humans is None:
        self.num_humans = 0
      if self.human_list is None:
        self.human_list = []
    else:
      self.header = std_msgs.msg.Header()
      self.image_header = std_msgs.msg.Header()
      self.num_humans = 0
      self.human_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs))
      _x = self.image_header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.num_humans
      buff.write(_get_struct_i().pack(_x))
      length = len(self.human_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.human_list:
        _x = val1
        buff.write(_get_struct_4i().pack(_x.num_body_key_points_with_non_zero_prob, _x.num_face_key_points_with_non_zero_prob, _x.num_right_hand_key_points_with_non_zero_prob, _x.num_left_hand_key_points_with_non_zero_prob))
        _v1 = val1.body_bounding_box
        _x = _v1
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.width, _x.height))
        _v2 = val1.face_bounding_box
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.width, _x.height))
        if len(val1.body_key_points_with_prob) != 25:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (25, len(val1.body_key_points_with_prob), 'val1.body_key_points_with_prob')))
        for val2 in val1.body_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.face_key_points_with_prob) != 70:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (70, len(val1.face_key_points_with_prob), 'val1.face_key_points_with_prob')))
        for val2 in val1.face_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.right_hand_key_points_with_prob) != 21:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (21, len(val1.right_hand_key_points_with_prob), 'val1.right_hand_key_points_with_prob')))
        for val2 in val1.right_hand_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.left_hand_key_points_with_prob) != 21:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (21, len(val1.left_hand_key_points_with_prob), 'val1.left_hand_key_points_with_prob')))
        for val2 in val1.left_hand_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.human_list is None:
        self.human_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_header.frame_id = str[start:end]
      start = end
      end += 4
      (self.num_humans,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.human_list = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.OpenPoseHuman()
        _x = val1
        start = end
        end += 16
        (_x.num_body_key_points_with_non_zero_prob, _x.num_face_key_points_with_non_zero_prob, _x.num_right_hand_key_points_with_non_zero_prob, _x.num_left_hand_key_points_with_non_zero_prob,) = _get_struct_4i().unpack(str[start:end])
        _v3 = val1.body_bounding_box
        _x = _v3
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _get_struct_4d().unpack(str[start:end])
        _v4 = val1.face_bounding_box
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _get_struct_4d().unpack(str[start:end])
        val1.body_key_points_with_prob = []
        for i in range(0, 25):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.body_key_points_with_prob.append(val2)
        val1.face_key_points_with_prob = []
        for i in range(0, 70):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.face_key_points_with_prob.append(val2)
        val1.right_hand_key_points_with_prob = []
        for i in range(0, 21):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.right_hand_key_points_with_prob.append(val2)
        val1.left_hand_key_points_with_prob = []
        for i in range(0, 21):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.left_hand_key_points_with_prob.append(val2)
        self.human_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs))
      _x = self.image_header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.num_humans
      buff.write(_get_struct_i().pack(_x))
      length = len(self.human_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.human_list:
        _x = val1
        buff.write(_get_struct_4i().pack(_x.num_body_key_points_with_non_zero_prob, _x.num_face_key_points_with_non_zero_prob, _x.num_right_hand_key_points_with_non_zero_prob, _x.num_left_hand_key_points_with_non_zero_prob))
        _v5 = val1.body_bounding_box
        _x = _v5
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.width, _x.height))
        _v6 = val1.face_bounding_box
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.width, _x.height))
        if len(val1.body_key_points_with_prob) != 25:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (25, len(val1.body_key_points_with_prob), 'val1.body_key_points_with_prob')))
        for val2 in val1.body_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.face_key_points_with_prob) != 70:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (70, len(val1.face_key_points_with_prob), 'val1.face_key_points_with_prob')))
        for val2 in val1.face_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.right_hand_key_points_with_prob) != 21:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (21, len(val1.right_hand_key_points_with_prob), 'val1.right_hand_key_points_with_prob')))
        for val2 in val1.right_hand_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
        if len(val1.left_hand_key_points_with_prob) != 21:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (21, len(val1.left_hand_key_points_with_prob), 'val1.left_hand_key_points_with_prob')))
        for val2 in val1.left_hand_key_points_with_prob:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.prob))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.human_list is None:
        self.human_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_header.frame_id = str[start:end]
      start = end
      end += 4
      (self.num_humans,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.human_list = []
      for i in range(0, length):
        val1 = openpose_ros_msgs.msg.OpenPoseHuman()
        _x = val1
        start = end
        end += 16
        (_x.num_body_key_points_with_non_zero_prob, _x.num_face_key_points_with_non_zero_prob, _x.num_right_hand_key_points_with_non_zero_prob, _x.num_left_hand_key_points_with_non_zero_prob,) = _get_struct_4i().unpack(str[start:end])
        _v7 = val1.body_bounding_box
        _x = _v7
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _get_struct_4d().unpack(str[start:end])
        _v8 = val1.face_bounding_box
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.width, _x.height,) = _get_struct_4d().unpack(str[start:end])
        val1.body_key_points_with_prob = []
        for i in range(0, 25):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.body_key_points_with_prob.append(val2)
        val1.face_key_points_with_prob = []
        for i in range(0, 70):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.face_key_points_with_prob.append(val2)
        val1.right_hand_key_points_with_prob = []
        for i in range(0, 21):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.right_hand_key_points_with_prob.append(val2)
        val1.left_hand_key_points_with_prob = []
        for i in range(0, 21):
          val2 = openpose_ros_msgs.msg.PointWithProb()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.prob,) = _get_struct_3d().unpack(str[start:end])
          val1.left_hand_key_points_with_prob.append(val2)
        self.human_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
